$(".msg").mouseover(function() { $(this).css("color", "#5F9F9F"); } )
$(".signout").mouseover(function() { $(this).css("color", "#96CDCD"); } )
$(".home").mouseover(function() { $(this).css("color", "#96CDCD"); } )
$(".profile").mouseover(function() { $(this).css("color", "#96CDCD"); } )
$(".help").mouseover(function() {$ (this).css("color", "#96CDCD"); } )

$(".msg").mouseout(function() { $(this).css("color", "white"); } )
$(".signout").mouseout(function() { $(this).css("color", "white"); } )
$(".home").mouseout(function() { $(this).css("color", "white"); } )
$(".profile").mouseout(function() { $(this).css("color", "white"); } )
$(".help").mouseout(function() {$ (this).css("color", "white"); } )
